export const COPY = {
  search: {
    placeholder: 'Buscar platillo…',
    results: (n: number) => `${n} resultado${n !== 1 ? 's' : ''}`,
    noResults: 'Sin resultados para esta búsqueda',
    searching: 'Buscando…',
  },
  dish: {
    unavailable: 'Agotado',
    arBadge: 'AR',
    viewDetail: 'Ver detalle',
    addToOrder: 'Pedir',
  },
  table: {
    label: (n: string | number) => `Mesa ${n}`,
  },
  editor: {
    saveSuccess: 'Cambios guardados',
    saveError: 'Error al guardar. Intenta de nuevo.',
    publishSuccess: '¡Menú publicado!',
    publishError: 'Error al publicar. Intenta de nuevo.',
    unsavedChanges: 'Tienes cambios sin guardar',
    publishing: 'Publicando…',
    saving: 'Guardando…',
    undoSuccess: 'Cambio deshecho',
    noMoreUndo: 'No hay más cambios que deshacer',
  },
  auth: {
    signIn: 'Iniciar sesión',
    signOut: 'Cerrar sesión',
    loading: 'Cargando…',
    error: 'Error al iniciar sesión. Verifica tus credenciales.',
  },
  errors: {
    generic: 'Algo salió mal. Intenta de nuevo.',
    notFound: 'No encontrado.',
    unauthorized: 'No tienes permiso para hacer esto.',
    networkError: 'Error de conexión. Verifica tu internet.',
  },
  empty: {
    dishes: 'No hay platillos en esta categoría.',
    menu: 'Este menú está vacío.',
    search: 'No se encontraron resultados.',
  },
  cart: {
    title: 'Tu pedido',
    empty: 'Aún no has agregado platos.',
    emptyHint: 'Toca un plato del menú para agregarlo.',
    addToCart: 'Agregar al pedido',
    added: 'Agregado al pedido',
    subtotal: 'Subtotal',
    orderViaWhatsApp: 'Pedir por WhatsApp',
    payHere: 'Pagar aquí',
    payHereSoon: 'Próximamente',
    checkoutTitle: 'Confirmar pedido',
    namePlaceholder: 'Tu nombre',
    phonePlaceholder: 'Tu teléfono (opcional)',
    notePlaceholder: 'Nota para el restaurante (opcional)',
    confirm: 'Confirmar pedido',
    sending: 'Enviando…',
    orderSent: '¡Pedido enviado!',
    orderError: 'No se pudo enviar el pedido. Intenta de nuevo.',
    nameRequired: 'Escribe tu nombre para continuar.',
    remove: 'Quitar',
    clear: 'Vaciar',
    forTable: (label: string) => `Mesa ${label}`,
    pickup: 'Para llevar',
    delivery: {
      modeLabel: 'Modo de entrega',
      dineIn: 'Comer aquí',
      takeout: 'Para llevar',
      delivery: 'A domicilio',
      addressPlaceholder: 'Dirección de entrega (calle, señas, ciudad)',
      addressRequired: 'Escribe la dirección de entrega.',
      phoneRequired: 'Escribe tu teléfono para el domicilio.',
    },
    forPickup: 'Para llevar',
    forDelivery: (address: string) => `Domicilio · ${address}`,
  },
  orders: {
    title: 'Pedidos',
    today: 'Hoy',
    history: 'Historial',
    emptyActive: 'No hay pedidos activos en este momento.',
    emptyDate: 'No hubo pedidos en esta fecha.',
    stats: {
      orders: 'Pedidos',
      revenue: 'Ventas',
      avgTicket: 'Ticket promedio',
    },
    status: {
      pending: 'Pendiente',
      confirmed: 'Confirmado',
      preparing: 'Preparando',
      ready: 'Listo',
      delivered: 'Entregado',
      completed: 'Completado',
      cancelled: 'Cancelado',
    },
    actions: {
      confirm: 'Confirmar',
      prepare: 'Preparar',
      ready: 'Listo',
      deliver: 'Entregar',
      cancel: 'Cancelar',
    },
  },
  kds: {
    title: 'Cocina',
    columns: {
      incoming: 'Nuevos',
      preparing: 'En preparación',
      ready: 'Listos',
    },
    actions: {
      startPreparing: '▶ Preparar',
      markReady: '✓ Listo',
      markDelivered: '✓ Entregado',
    },
    pickup: 'Para llevar',
    empty: 'Sin pedidos por ahora',
    orderNumber: (n: string) => `#${n}`,
    elapsed: (min: number) => `${min} min`,
    exit: 'Salir',
  },
  crm: {
    title: 'Clientes',
    searchPlaceholder: 'Buscar por nombre o teléfono…',
    empty: 'Aún no hay clientes registrados.',
    emptyHint: 'Los clientes se crean automáticamente cuando hacen un pedido con su teléfono.',
    noSearchResults: 'Ningún cliente coincide con la búsqueda.',
    exportCsv: 'Exportar CSV',
    stats: {
      customers: 'Clientes',
      vip: 'VIP',
      inactive: 'Inactivos',
    },
    table: {
      customer: 'Cliente',
      orders: 'Pedidos',
      spent: 'Gasto total',
      avgTicket: 'Ticket prom.',
      lastOrder: 'Último pedido',
    },
    drawer: {
      ordersTitle: 'Historial de pedidos',
      ordersEmpty: 'Sin pedidos registrados en la ventana reciente.',
      noteTitle: 'Nota interna',
      notePlaceholder: 'Preferencias, alergias, datos útiles…',
      noteSave: 'Guardar nota',
      noteSaved: 'Nota guardada',
      memberSince: 'Cliente desde',
      close: 'Cerrar',
    },
    neverOrdered: 'Nunca',
  },
  inventory: {
    title: 'Inventario',
    tabs: {
      ingredients: 'Ingredientes',
      recipes: 'Recetas',
      movements: 'Movimientos',
      alerts: 'Alertas',
    },
    ingredients: {
      empty: 'Aún no hay ingredientes.',
      emptyHint: 'Crea tu primer ingrediente para empezar a controlar stock y food cost.',
      add: 'Nuevo ingrediente',
      name: 'Nombre',
      namePlaceholder: 'Ej: Queso mozzarella',
      unit: 'Unidad',
      currentStock: 'Stock actual',
      minimumStock: 'Stock mínimo',
      costPerUnit: 'Costo por unidad',
      category: 'Categoría',
      categoryPlaceholder: 'Ej: Lácteos (opcional)',
      save: 'Guardar',
      saving: 'Guardando…',
      cancel: 'Cancelar',
      registerPurchase: 'Registrar compra',
      lowStock: 'Bajo mínimo',
    },
    movements: {
      empty: 'Sin movimientos registrados.',
      quantity: 'Cantidad',
      quantityPlaceholder: 'Cantidad',
      note: 'Nota',
      notePlaceholder: 'Nota (opcional)',
      submit: 'Registrar',
      types: {
        purchase: 'Compra',
        sale: 'Venta',
        waste: 'Merma',
        adjustment: 'Ajuste',
      },
    },
    recipes: {
      empty: 'Selecciona un plato para definir su receta.',
      selectMenu: 'Menú',
      selectDish: 'Plato',
      addIngredient: 'Agregar ingrediente',
      yield: 'Rinde (porciones)',
      foodCost: 'Food cost',
      perPortion: 'por porción',
      save: 'Guardar receta',
      saved: 'Receta guardada',
      noIngredients: 'Agrega ingredientes a la receta para calcular el food cost.',
      remove: 'Quitar',
    },
    alerts: {
      empty: 'Todo el inventario está sobre el mínimo. 🎉',
      banner: (n: number) =>
        `${n} ingrediente${n !== 1 ? 's' : ''} bajo el stock mínimo`,
      viewInventory: 'Ver inventario',
      stockOf: (current: string, min: string) => `${current} / mín. ${min}`,
    },
  },
  pos: {
    title: 'POS',
    pin: {
      title: 'Acceso al POS',
      subtitle: 'Ingresa tu PIN de empleado para continuar',
      error: 'PIN incorrecto. Intenta de nuevo.',
      noPinConfigured: 'No hay PIN configurado. Configúralo en Configuración → Empleados.',
      validating: 'Validando…',
      clear: 'Borrar',
      lock: 'Bloquear',
    },
    tables: {
      title: 'Mesas',
      free: 'Libre',
      occupied: 'Ocupada',
      pending: 'Pendiente',
      empty: 'No hay mesas configuradas. Créalas en Mesas & QR.',
      account: (n: number) => `${n} pedido${n !== 1 ? 's' : ''} en cuenta`,
    },
    menu: {
      searchPlaceholder: 'Buscar plato…',
      all: 'Todos',
      backToTables: 'Mesas',
    },
    cart: {
      title: 'Comanda',
      empty: 'Toca platos del menú para agregarlos.',
      sendToKitchen: 'Enviar a cocina',
      sending: 'Enviando…',
      sent: 'Comanda enviada',
      total: 'Total',
      account: 'Cuenta de la mesa',
      closeCheck: 'Cobrar cuenta',
    },
    check: {
      title: 'Cerrar cuenta',
      total: 'Total a cobrar',
      method: 'Método de pago',
      methods: {
        cash: 'Efectivo',
        card: 'Tarjeta',
        sinpe: 'SINPE',
        yape: 'Yape',
        other: 'Otro',
      },
      cashGiven: 'Efectivo recibido',
      change: 'Vuelto',
      reference: 'Referencia (opcional)',
      confirm: 'Confirmar pago',
      processing: 'Procesando…',
      done: 'Cuenta cerrada',
      insufficientCash: 'El efectivo no cubre el total.',
      cancel: 'Cancelar',
    },
  },
  reservations: {
    title: 'Reservaciones',
    publicTitle: 'Reservar mesa',
    publicSubtitle: 'Completa los datos y te confirmamos por WhatsApp.',
    menuLink: 'Reservar mesa',
    form: {
      name: 'Nombre',
      namePlaceholder: 'Tu nombre',
      phone: 'Teléfono',
      phonePlaceholder: 'Tu teléfono',
      date: 'Fecha',
      time: 'Hora',
      partySize: 'Personas',
      note: 'Nota (opcional)',
      notePlaceholder: 'Alergias, ocasión especial…',
      submit: 'Reservar',
      sending: 'Enviando…',
      nameRequired: 'Escribe tu nombre para continuar.',
      phoneRequired: 'Escribe tu teléfono para continuar.',
    },
    confirmation: {
      title: '¡Reserva recibida!',
      number: (n: string) => `Reserva #${n}`,
      detail: 'Te confirmaremos por WhatsApp en breve.',
      backToMenu: 'Volver al menú',
    },
    status: {
      pending: 'Pendiente',
      confirmed: 'Confirmada',
      seated: 'En mesa',
      cancelled: 'Cancelada',
      no_show: 'No llegó',
    },
    actions: {
      confirm: 'Confirmar',
      seat: 'Sentar',
      cancel: 'Cancelar',
      noShow: 'No llegó',
      newReservation: 'Nueva reserva',
    },
    stats: {
      total: 'Reservas',
      pending: 'Pendientes',
      guests: 'Comensales',
    },
    empty: 'No hay reservas para esta fecha.',
    people: (n: number) => `${n} persona${n !== 1 ? 's' : ''}`,
    whatsappMessage: 'Nueva reserva',
  },
} as const
